### ISSUE TITLE
Add Anamnesis Pose Category to Mod Upload Screen

### ISSUE THREAD

**Issue by AncientAzem** [XivRepo/XivRepo-Frontend#13]
Right now the only category available for selection is `Cmt Pose` This needs to be updated to allow the selection of Anamnesis poses or CMT Poses.

**Comment by XNBlank** [comment]
Done. https://github.com/XivRepo/XivRepo-ApiServer/commit/c7fafd81d4569f643fba6ad3ee6305d28f29cb4a
