### ISSUE TITLE
Associate CMT and Anamnesis pose extensions in file uploads

### ISSUE THREAD

**Issue by AncientAzem** [XivRepo/XivRepo-Frontend#14]

**Comment by XNBlank** [comment]
Done 
https://github.com/XivRepo/XivRepo-ApiServer/commit/63a2ac1be511f84c76e5fbf7f019ed3d70b89912
https://github.com/XivRepo/XivRepo-Frontend/commit/e28afd2dcadbdd1633ac25f8c2b4255de5b82c56
