### ISSUE TITLE
Problem where trying to follow someone while not logged in doesn't redirect you to log in

### ISSUE THREAD

**Issue by EARTHTOZER0** [XivRepo/XivRepo-Frontend#2]
**Describe the bug**
Problem where trying to follow someone while not logged in doesn't redirect you to log in.

**To Reproduce**
1. Go to 'A mod of choice while not logged in'
2. Click on 'Follow'

**Expected behavior**
Nothing happens. (No redirection to log in)

**Comment by XNBlank** [comment]
Follow button no longer shows up when you're not logged in.
