### ISSUE TITLE
Add NSFW Flags to the Site

### ISSUE THREAD

**Issue by AncientAzem** [XivRepo/XivRepo-Frontend#24]
We need to have an NSFW flagging system implemented onto the site. This would be separate from the user submitted tagging system. This system would have the following features:

- Upon mod creation/editing an NSFW flag should be available to add
- NSFW Mods will not be viewable by users who are logged out
- NSFW Mod visibility can be toggled on and off for a user in their settings
- NSFW Mods should be able to be filtered in/out regardless of user settings on the search page via a filter toggle

**Comment by DevJinnial** [comment]
The backend will need to support the custom tagging system before this can be fully implemented. In addition, the NSFW toggle on the search page should be shown separate from the tag selector as it's own toggle if possible and doesn't take too much time to implement. This is not needed for initial release, but can be a UI refinement later on down the line.

**Comment by AncientAzem** [comment]
One thing of note here. Here are the fields I am using in the front-end awaiting the backend to be updated:

- User profile shall store show_nsfw: boolean which the adult content visibility is driven by.
-  Mods now have a field called is_nsfw: boolean which indicate if the content is sfw or nsfw

This can be seen in PR #35
