### ISSUE TITLE
No option for "Gear Mod" "Anamnesis/CMT poses" "Reshade/Gshade Presets"

### ISSUE THREAD

**Issue by EARTHTOZER0** [XivRepo/XivRepo-Frontend#3]
**Is your feature request related to a problem? Please describe.**
"Gear Mod" "Anamnesis/CMT poses" "Reshade/Gshade Presets" are normally options you can choose on previous modding websites.

**Describe the solution you'd like**
Options for "Gear Mod" "Anamnesis/CMT poses" "Reshade/Gshade Presets" when creating a New Mod and choosing a Category.

**Describe alternatives you've considered**
Eating playdough

**Comment by XNBlank** [comment]
Fixed.
