### ISSUE TITLE
An increase max size for preview images

### ISSUE THREAD

**Issue by AncientAzem** [XivRepo/XivRepo-Frontend#45]
An increase max size for preview images need to be made. Right now it is 250kb which is wayyyy too small for most images. 500kb to 1mb would be a good max for this

**Comment by AncientAzem** [comment]
@XNBlank once you get the backend settings updated just lemme know here and I will update the frontend to reflect this.

**Comment by XNBlank** [comment]
Will be updated to max 1MiB in the next api update.
