### ISSUE TITLE
Mod sections on the Front Page

### ISSUE THREAD

**Issue by EARTHTOZER0** [XivRepo/XivRepo-Frontend#5]
**Is your feature request related to a problem? Please describe.**
Nah no problem

**Describe the solution you'd like**
A section on the main page to display "Newest Mods", "Most Popular" and "Latest Releases from Subscribed Authors"

**Describe alternatives you've considered**
Consuming an all time favorite meal of crayons and lighter fluid.

**Comment by XNBlank** [comment]
This was something I am currently working on. It'll be pushed out soon. :)

**Comment by XNBlank** [comment]
I've added two sections to the homepage in https://github.com/XivRepo/XivRepo-Frontend/commit/d83436acb4f2fc7199cabb1c3481d941649f5035

More can definitely be added in the future, when there are more mods on the site. Could even add randomized categories, and I also want to eventually added a featured section (might replace the banner).
