### ISSUE TITLE
What makes a mod popular

### ISSUE THREAD

**Issue by EARTHTOZER0** [XivRepo/XivRepo-Frontend#9]
On the front page, when viewing the "Popular Mod" Section and clicking on "View more Popular Mods". 

It shows that Popular mods are indicated by how many "Follows" the mod has. 

I feel that a Popular mod should be indicated by how many "Downloads" it has instead.

**Comment by XNBlank** [comment]
Updated https://github.com/XivRepo/XivRepo-Frontend/pull/10
